# Machine Learning (Session 15)
install.packages('tidyverse')
install.packages('UsingR')
install.packages('manipulate')
install.packages('broom')
install.packages('BSDA')
install.packages('ggfortify')
install.packages("caret")
install.packages("kernlab")
install.packages("ISLR")
install.packages("Hmisc")
install.packages("gridExtra")
library(tidyverse)
library(UsingR)
library(manipulate)
library(broom)
library(BSDA)
library(ggfortify)
library(caret)
library(kernlab)
library(ISLR)
library(Hmisc)
library(gridExtra)


# REGRESSION ANALYSIS 2 (SESSION 14)
install.packages('tidyverse')
install.packages('UsingR')
install.packages('manipulate')
install.packages('broom')
install.packages('BSDA')
install.packages('ggfortify')
library(UsingR)
library(manipulate)
library(broom)
library(BSDA)
library(ggfortify)


#Project (Group 2 - Dangote Cement & MTN Stock)
install.packages("tidyverse")
install.packages("quantmod")
install.packages("forecast")
install.packages("TTR")
install.packages("ggplot2")
install.packages("lubridate")
library(tidyverse)
library(quantmod)
library(forecast)
library(TTR)
library(ggplot2)
library(lubridate)


#Regression (Session 13)
install.packages('tidyverse')
install.packages('UsingR')
install.packages('manipulate')
install.packages('broom')
install.packages('BSDA')
install.packages('ggfortify')
library(tidyverse)
library(UsingR)
library(manipulate)
library(broom)
library(BSDA)
library(ggfortify)
library(plotly)


#Statistical Inference (Session 12)
install.packages("tidyverse")
install.packages("UsingR")
install.packages("BSDA")
library(tidyverse)
library(usingR)
library(BSDA)


#Plotting Geocoding in R (Session 11)
install.packages("tidygeocoder")
install.packages("sf")
install.packages("mapview")
install.packages("leaflet")
install.packages("plotly")
install.packages("janitor")
install.packages("usethis")
library(tidyverse)
library(tidygeocoder)
library(sf)
library(mapview)
library(leaflet)
library(plotly)
library(janitor)
library(usethis)


#Data Visualization (Session 10)
install.packages("tidyverse")
install.packages("DataExplorer")
install.packages("explore")
install.packages("SmartEDA")
install.packages("wordcloud2")
install.packages("readxl")
install.packages("plotly")
library(tidyverse)
library(DataExplorer)
library(explore)
library(SmartEDA)
library(wordcloud2)
library(readxl)
library(plotly)


#EDA & Auto EDA (Session 9)
install.packages("tidyverse")
install.packages("learnr")
install.packages("DataExplorer")
install.packages("explore")
install.packages("SmartEDA")
install.packages("wordcloud2")
install.packages("readxl")
install.packages("tidytext")
install.packages("wordcloud")
install.packages("topicmodels")
install.packages("tm")
install.packages("visNetwork")
install.packages("qdapRegex")
install.packages("syuzhet")
install.packages("ggraph")
library(tidyverse)
library(learnr)
library(DataExplorer)
library(explore)
library(SmartEDA)
library(wordcloud2)
library(readxl)
library(tidytext)
library(wordcloud)
library(topicmodels)
library(tm)
library(visNetwork)
library(qdapRegex)
library(syuzhet)
library(ggraph)


#Cleaning Data & Regular Expression (Session 7) - No Libraries needed
#Data Gathering in R (Session 6) - No Libraries Needed
#Programming in R (Session 5) - No Libraries Needed
#Probability Distributions (Session 3) - No Libraries Needed
#Descriptive Statistics (Session 2) - No Libraries Needed
#Data Science Toolkits (Session 1) - No Libraries Needed


data(package = .packages(all.available = TRUE))
#to list the data sets in all *available* packages.

data()
#to check out all available data on R